# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Research', url: 'research'}
- {name: 'Publications', url: 'publications'}
- {name: 'News',       url: 'news'}
- {name: 'People',      url: 'people'}
- {name: 'Resources',	url: 'resources'}
- {name: 'Job Opportunities',	url: 'opportunities'}
- {name: 'Contact',            url: 'contact'}

sharing_button_prompt: 'Feel free to share!'

#related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
